Imported from /tmp/iceweasel_5.0.orig.tar.bz2.

diff --git a/js/src/Makefile.in b/js/src/Makefile.in
--- a/js/src/Makefile.in
+++ b/js/src/Makefile.in
@@ -59,9 +59,8 @@ ifndef JS_DISABLE_SHELL
 DIRS += shell
 endif
 
-# FIXME: bug 515383 covers getting these working on wince
-# bug 530688 covers Android
-ifneq (,$(filter-out WINCE ANDROID,$(OS_ARCH)))
+# FIXME: bug 530688 covers getting these working on Android
+ifneq (,$(filter-out ANDROID,$(OS_ARCH)))
 ifdef ENABLE_TESTS
 DIRS += jsapi-tests
 endif
@@ -88,7 +87,7 @@ MODULE_OPTIMIZE_FLAGS = -O2 -ip
 endif
 else # not INTEL_CXX
 
-MODULE_OPTIMIZE_FLAGS = -O3 -fstrict-aliasing
+MODULE_OPTIMIZE_FLAGS = -O3 -fstrict-aliasing -fno-stack-protector
 
 # We normally want -fomit-frame-pointer, but we want an explicit
 # -fno-omit-frame-pointer if we're using a sampling profiler.
@@ -108,6 +107,9 @@ MODULE_OPTIMIZE_FLAGS = -O2
 endif
 endif
 
+ifeq ($(OS_ARCH),WINNT)
+NO_PROFILE_GUIDED_OPTIMIZE = 1
+endif
 
 # JavaScript must be built shared, even for static builds, as it is used by
 # other modules which are always built shared. Failure to do so results in
@@ -157,6 +159,7 @@ CPPSRCS		= \
 		jsnum.cpp \
 		jsobj.cpp \
 		json.cpp \
+		jsonparser.cpp \
 		jsopcode.cpp \
 		jsparse.cpp \
 		jsproxy.cpp \
@@ -214,9 +217,11 @@ INSTALLED_HEADERS = \
 		jslock.h \
 		jslong.h \
 		jsmath.h \
+		jsnum.h \
 		jsobj.h \
 		jsobjinlines.h \
 		json.h \
+		jsonparser.h \
 		jsopcode.tbl \
 		jsopcode.h \
 		jsopcodeinlines.h \
@@ -255,6 +260,19 @@ INSTALLED_HEADERS = \
 		jsval.h \
 		jsvalue.h \
 		prmjtime.h \
+		$(NULL)
+
+###############################################
+# BEGIN include sources for low-level code shared with Gecko
+#
+VPATH		+= \
+		$(srcdir)/../../mfbt \
+		$(NULL)
+
+EXPORTS_NAMESPACES = mozilla
+
+EXPORTS_mozilla = \
+		Util.h          \
 		$(NULL)
 
 ifdef ENABLE_TRACEJIT
@@ -300,13 +318,6 @@ CPPSRCS += \
 		Writer.cpp     \
 		$(NULL)
 
-ifdef WINCE
-# don't need -c
-AS_DASH_C_FLAG =
-ASFLAGS += -arch 6
-ASFILES += jswince.asm
-endif
-
 endif # ENABLE_TRACEJIT
 ifdef ENABLE_METHODJIT
 
@@ -335,6 +346,11 @@ ifeq (86, $(findstring 86,$(TARGET_CPU)))
 ifeq (x86_64, $(TARGET_CPU))
 ifdef _MSC_VER
 ASFILES +=	TrampolineMasmX64.asm
+endif
+ifeq ($(OS_ARCH),WINNT)
+ifdef GNU_CC
+ASFILES +=	TrampolineMingwX64.s
+endif
 endif
 ifdef SOLARIS_SUNPRO_CXX
 ASFILES +=	TrampolineSUNWX64.s
@@ -482,7 +498,7 @@ else
 CPPSRCS += pm_stub.cpp
 endif
 
-ifeq (,$(filter-out WINNT WINCE,$(OS_ARCH)))
+ifeq (,$(filter-out WINNT,$(OS_ARCH)))
 INSTALLED_HEADERS += jscpucfg.h
 endif
 
@@ -490,7 +506,7 @@ EXPORTS = $(INSTALLED_HEADERS)
 
 DASH_R		= -r
 
-ifneq (,$(filter OS2 WINCE WINNT,$(OS_ARCH)))
+ifneq (,$(filter OS2 WINNT,$(OS_ARCH)))
 SDK_LIBRARY = $(IMPORT_LIBRARY)
 else
 SDK_LIBRARY = $(SHARED_LIBRARY)
@@ -524,7 +540,7 @@ endif
 default::
 
 ifneq (,$(CROSS_COMPILE)$(filter-out WINNT OS2,$(OS_ARCH)))
-ifneq (,$(filter-out SYMBIAN WINCE,$(OS_ARCH)))
+ifneq (,$(filter-out SYMBIAN,$(OS_ARCH)))
 # nsinstall doesn't get built until we enter config/ in the exports phase,
 # so we'll have to manually ensure it gets built here if we want to use
 # $(EXPORTS)
@@ -548,7 +564,6 @@ distclean clean::
 		$(call SUBMAKE,$@,ctypes/libffi)
 endif
 
-ifdef MOZ_SYNC_BUILD_FILES
 # Because the SpiderMonkey can be distributed and built independently
 # of the Mozilla source tree, it contains its own copies of many of
 # the files used by the top-level Mozilla build process, from the
@@ -563,36 +578,98 @@ ifdef MOZ_SYNC_BUILD_FILES
 # Some files are reasonable to diverge; for  example,
 # js/config/autoconf.mk.in doesn't need most of the stuff in
 # config/autoconf.mk.in.
-check-sync-dirs = $(PYTHON) $(srcdir)/config/check-sync-dirs.py
-check::
-	$(check-sync-dirs) $(srcdir)/config $(MOZ_SYNC_BUILD_FILES)/config
-	$(check-sync-dirs) $(srcdir)/build $(MOZ_SYNC_BUILD_FILES)/build
+check-sync-dirs-cmd = $(PYTHON) $(srcdir)/config/check-sync-dirs.py
+check-sync-dirs:
+	$(check-sync-dirs-cmd) $(srcdir)/config $(MOZ_SYNC_BUILD_FILES)/config
+	$(check-sync-dirs-cmd) $(srcdir)/build $(MOZ_SYNC_BUILD_FILES)/build
 
-check-valgrind::
-	$(check-sync-dirs) $(srcdir)/config $(MOZ_SYNC_BUILD_FILES)/config
-	$(check-sync-dirs) $(srcdir)/build $(MOZ_SYNC_BUILD_FILES)/build
+ifdef MOZ_SYNC_BUILD_FILES
+check:: check-sync-dirs
 endif
 
 # The "find any vanilla new/new[] calls" script is tailored to Linux, so
 # only run it there.  That should be enough to catch any such calls that
 # creep in.
-ifeq ($(OS_ARCH),Linux)
-check::
+check-vanilla-new:
 	$(srcdir)/config/find_vanilla_new_calls $(LIBRARY)
+
+ifeq ($(OS_ARCH),Linux)
+check:: check-vanilla-new
 endif
 
-ifdef ENABLE_TRACEJIT
-ifndef WINCE
+# Help ensure that the number of OOM errors in SpiderMonkey doesn't increase.
+# If the number of OOM errors changes, update the number below. We intend this
+# number to go down over time, by fixing OOMs.
+check-ooms:
+	$(wildcard $(RUN_TEST_PROGRAM)) $(PYTHON) -u $(srcdir)/config/find_OOM_errors.py --regression 125
+
+ifeq ($(MOZ_DEBUG),1)
+#check:: check-ooms
+endif
+
+## Prevent regressing in our deprecation of non-preferred memory management functions.
+# We use all the files in the distribution so that different configurations
+# don't give different results. We skip the contents of objdirs using |find|
+# (it can't be done with %-expansion, because the files we want to skip aren't
+# in the vpath).
+ALL_FILES=$(shell find $(srcdir) \( -name "*.cpp" -o -name "*.h" \) -not -path "*/dist/*")
+check-malloc-function-usage: $(filter-out %jsutil.h %jscntxt.h, $(ALL_FILES))
+
+	# js_malloc and friends are only used by other memory managers, and should
+	# never be used elsewhere directly.
+	$(srcdir)/config/check_source_count.py "\bjs_malloc\b" 0 \
+		"in Makefile.in" "cx->malloc_ or rt->malloc_" $^
+	$(srcdir)/config/check_source_count.py "\bjs_calloc\b" 0 \
+		"in Makefile.in" "cx->calloc_ or rt->calloc_" $^
+	$(srcdir)/config/check_source_count.py "\bjs_realloc\b" 0 \
+		"in Makefile.in" "cx->realloc_ or rt->realloc_" $^
+	$(srcdir)/config/check_source_count.py "\bjs_free\b" 0 \
+		"in Makefile.in" "cx->free_" $^
+
+	# We desire these numbers to go down, not up. See "User guide to memory
+	# management within SpiderMonkey" in jsutil.h.
+	$(srcdir)/config/check_source_count.py OffTheBooks:: 54 \
+		"in Makefile.in" "{cx,rt}->{new_,new_array,malloc_,calloc_,realloc_}" $^
+	# This should go to zero, if possible.
+	$(srcdir)/config/check_source_count.py UnwantedForeground:: 35 \
+		"in Makefile.in" "{cx,rt}->{free_,delete_,array_delete}" $^
+
+ifneq ($(OS_ARCH),WINNT) # FIXME: this should be made work on Windows too.
+check:: check-malloc-function-usage
+endif
+
 JITFLAGS = ,m,j,mj,mjp,am,amj,amjp,amd
-check::
+check-jit-test::
 	$(wildcard $(RUN_TEST_PROGRAM)) $(PYTHON) -u $(srcdir)/jit-test/jit_test.py \
 	        --no-slow --no-progress --tinderbox --jitflags=$(JITFLAGS) $(DIST)/bin/js$(BIN_SUFFIX)
 
-check-valgrind::
+check-jit-test-valgrind::
 	$(wildcard $(RUN_TEST_PROGRAM)) $(PYTHON) -u $(srcdir)/jit-test/jit_test.py \
 	        --valgrind --no-slow --no-progress --tinderbox --jitflags=$(JITFLAGS) $(DIST)/bin/js$(BIN_SUFFIX)
-endif
-endif
+
+
+# jstests doesn't have a --jitflags option, so we need to loop, updating the
+# exit code (RC) after each invocation.
+# FIXME: MethodJIT doesn't work for 1 test case (bug 644393), so
+# --no-extensions is set to skip that test. Remove as soon as possible.
+check-jstests:
+	RC=0; \
+	for f in `echo "$(JITFLAGS)" | tr ',' '\n'`; \
+		do \
+			$(wildcard $(RUN_TEST_PROGRAM)) $(PYTHON) -u $(srcdir)/tests/jstests.py \
+				--tinderbox --no-progress \
+				--no-extensions \
+				--timeout 300 \
+				--args="`echo $$f | sed 's/\(.\)/ -\1/g'`" \
+				$(DIST)/bin/js$(BIN_SUFFIX); \
+			RC=$$(( $$RC || $$?)); \
+		done; \
+	exit $$RC
+
+
+check:: check-jit-test
+#check:: check-jstests
+check-valgrind:: check-jit-test-valgrind
 
 DIST_GARBAGE = config.cache config.log config.status \
    config/autoconf.mk \
@@ -600,11 +677,11 @@ DIST_GARBAGE = config.cache config.log config.status \
 
 distclean::
 	cat unallmakefiles | $(XARGS) rm -f
-	rm -f $(DIST_GARBAGE)
+	$(RM) $(DIST_GARBAGE)
 
 # our build system doesn't handle subdir srcs very gracefully today
 export::
-	mkdir -p nanojit
+	$(MKDIR) -p nanojit
 
 DEFINES		+= -DEXPORT_JS_API
 
@@ -651,8 +728,8 @@ EXTRA_DSO_LDOPTS += C:/Program\ Files/Intel/VTune/Analyzer/Lib/VtuneApi.lib
 LIBS +=  C:/Program\ Files/Intel/VTune/Analyzer/Lib/VtuneApi.lib
 endif
 
-# BeOS and HP-UX do not require the extra linking of "-lm"
-ifeq (,$(filter BeOS HP-UX WINNT WINCE OpenVMS OS2,$(OS_ARCH)))
+# HP-UX does not require the extra linking of "-lm"
+ifeq (,$(filter HP-UX WINNT OS2,$(OS_ARCH)))
 EXTRA_LIBS	+= -lm
 endif
 
@@ -678,6 +755,23 @@ EXTRA_LIBS	+= -ldl
 endif
 ifeq ($(OS_ARCH),OSF1)
 EXTRA_LIBS	+= -lc_r
+endif
+# Silence warnings on AIX/HP-UX from non-GNU compilers
+ifndef GNU_CC
+ifeq ($(OS_ARCH),AIX)
+# Suppress warnings from xlC
+# 1540-1281: offsetof() on null non-POD types
+# 1540-1608: anonymous unions using static data members
+CFLAGS		+= -qsuppress=1540-1281 -qsuppress=1540-1608
+CXXFLAGS	+= -qsuppress=1540-1281 -qsuppress=1540-1608
+endif
+ifeq ($(OS_ARCH),HP-UX)
+# Suppress warnings from aCC
+# 3055: anonymous unions declaring types
+# 4189: offsetof() on non-POD types
+CFLAGS		+= +W3055,4189
+CXXFLAGS	+= +W3055,4189
+endif
 endif
 ifeq ($(OS_ARCH),SunOS)
 ifeq ($(TARGET_CPU),sparc)
@@ -742,17 +836,12 @@ export:: jsautocfg.h
 
 ifeq (,$(CROSS_COMPILE)$(GNU_CC)$(filter-out WINNT,$(OS_ARCH)))
 jsautocfg.h:
-	touch $@
-else
-ifeq ($(OS_ARCH),WINCE)
-jsautocfg.h:
-	touch $@
+	$(TOUCH) $@
 else
 jsautocfg.h: jscpucfg$(HOST_BIN_SUFFIX)
-	@rm -f $@ jsautocfg.tmp
+	@$(RM) $@ jsautocfg.tmp
 	./jscpucfg > jsautocfg.tmp
 	mv jsautocfg.tmp $@
-endif
 endif
 
 # jscpucfg is a strange target
@@ -778,13 +867,8 @@ jscpucfg: jscpucfg.o
 	$(HOST_CXX) $(HOST_CXXFLAGS) $(JSCPUCFG_DEFINES) $(DEFINES) -o $@ $<
 endif
 else
-ifeq ($(OS_ARCH),WINCE)
-jscpucfg$(HOST_BIN_SUFFIX):
-	echo no need to build jscpucfg $<
-else
 jscpucfg$(HOST_BIN_SUFFIX): jscpucfg.cpp Makefile.in
 	$(HOST_CXX) $(HOST_CXXFLAGS) $(JSCPUCFG_DEFINES) $(DEFINES) $(NSPR_CFLAGS) $(HOST_OUTOPTION)$@ $<
-endif
 endif
 
 # Compute the linker flags that programs linking against SpiderMonkey should
@@ -809,7 +893,7 @@ JS_CONFIG_LIBS=$(EXTRA_DSO_LDOPTS) $(OS_LIBS) $(EXTRA_LIBS)
 # this rule.
 at=@
 js-config: js-config.in Makefile $(DEPTH)/config/autoconf.mk $(topsrcdir)/config/config.mk $(topsrcdir)/config/rules.mk
-	rm -f js-config.tmp
+	$(RM) js-config.tmp
 	sed < $< > js-config.tmp \
 	-e 's|$(at)prefix$(at)|$(prefix)|' \
 	-e 's|$(at)exec_prefix$(at)|$(exec_prefix)|' \
@@ -885,7 +969,7 @@ NANOJIT_CENTRAL_LOCAL=$(CURDIR)/nanojit-central
 CUR_REPO=$(srcdir)/../..
 
 update-nanojit:
-	rm -Rf $(NANOJIT_CENTRAL_LOCAL) import-splicemap import-revmap
+	$(RM) -r $(NANOJIT_CENTRAL_LOCAL) import-splicemap import-revmap
 	hg clone $(NANOJIT_CENTRAL_REPO) $(NANOJIT_CENTRAL_LOCAL)
 	python $(srcdir)/find-child.py \
 	                   --src=$(NANOJIT_CENTRAL_LOCAL) \
